#!/bin/sh -eu

gz=$(command -v pigz || command -v gzip)

$gz -cd flex.tar.gz  | tar -x
cd flex*/

ac_cv_func_malloc_0_nonnull=yes \
ac_cv_func_realloc_0_nonnull=yes \
./configure --disable-shared \
            --enable-static \
            --prefix=$PREFIX
make
make check
make install
